Repository Read-bird/readbird-fe, pull requests merged in 2023-12, with the labels that each got.

#2 feat. deploy.yml 파일 생성
  .github/workflows/deploy.yml
Labels: enhancement

#4 홈 기본 화면 오류 수정
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/assets/images/Images.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/templates/HomeTemplate/Plan/Dots/Dots.tsx
  src/components/templates/HomeTemplate/Styled.tsx
  src/components/templates/HomeTemplate/Week/Styled.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/index.tsx
  src/styles/sweet-alert.css
  src/utils/Alert/Alert.ts
  src/utils/Alert/index.ts
  src/utils/Alert/typed.ts
  src/utils/index.ts
Labels: bug

#5 홈 캘린더 화면 UI 구현
  .github/workflows/deploy.yml
  src/App.tsx
  src/api/types/planRecord.ts
  src/assets/icons/IconBook.tsx
  src/assets/icons/IconCalendar.tsx
  src/assets/icons/IconDayBirdMini.tsx
  src/assets/icons/IconReact.tsx
  src/assets/icons/index.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Calendar/WeekCalendar.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Loadable/Loadable.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Loading/index.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/common/ProtectedLogin/ProtectedLogin.tsx
  src/components/common/ProtectedLogin/index.tsx
  src/components/common/Spacing/Spacing.tsx
  src/components/templates/AppTemplate/AppTemplate.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/HomeTemplate/Month/Styled.tsx
  src/components/templates/HomeTemplate/Plan/Dots/Dots.tsx
  src/components/templates/HomeTemplate/Styled.tsx
  src/components/templates/HomeTemplate/Week/Styled.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/LoadingTemplate/LoadingTemplate.tsx
  src/constants/plan.ts
  src/mocks/index.ts
  src/mocks/planRecord.ts
  src/routers/appRouter.tsx
  src/store/reducers/index.ts
  src/store/reducers/userPlan.ts
  src/store/state/store.ts
  src/styles/calendar.css
  src/styles/global-style.ts
  src/styles/sweet-alert.css
  src/utils/Alert/Alert.ts
  src/utils/classname/function.ts
  src/utils/function.ts
  tsconfig.paths.json
Labels: enhancement

#7 Feature/dw
  package-lock.json
  src/App.tsx
  src/api/axios.ts
  src/api/types/index.ts
  src/api/types/login.ts
  src/assets/images/BtnKakaoLogin.tsx
  src/assets/images/MainLogo.tsx
  src/components/common/Form/InputLabel.tsx
  src/components/common/Form/SelectLabel.tsx
  src/components/common/Modal/Modal.tsx
  src/components/templates/AppTemplate/AppTemplate.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/LoginTemplate/KakaoCallback/CallbackTemplate.tsx
  src/components/templates/LoginTemplate/KakaoCallback/index.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/components/templates/LoginTemplate/LoginTemplate.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/PlanModalTemplate/PlanModalTemplate.tsx
  src/components/templates/PlanModalTemplate/Register/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/Register/index.tsx
  src/constants/colors.ts
  src/mocks/planRecord.ts
  src/pages/AppLogin.tsx
  src/pages/KakaoCallback.tsx
  src/routers/appRouter.tsx
  src/store/reducers/userSlice.ts
  src/styles/reset.css
Labels: enhancement

#9 경로 수정 및 .env 설정 수정
  .github/workflows/deploy.yml
  .gitignore
  src/App.tsx
  src/api/axios.ts
  src/components/common/Calendar/WeekCalendar.tsx
  src/components/common/ProtectedLogin/ProtectedLogin.tsx
  src/components/templates/AppTemplate/AppTemplate.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/pages/AppRoot.tsx
  src/routers/appRouter.tsx
  src/store/reducers/userPlan.ts
  src/utils/errors/errors.ts
  src/utils/errors/index.ts
Labels: bug

#10 fix. 로그인 버튼 경로 오류 수정
  src/components/templates/LoginTemplate/LoginBtn.tsx
Labels: bug

#11 환경변수 오류 수정
  .github/workflows/deploy.yml
  .gitignore
  src/api/axios.ts
  src/api/types/book.ts
  src/api/types/planRegister.ts
  src/components/common/Form/InputLabel.tsx
  src/components/common/Search/SearchList.tsx
  src/components/common/Search/index.tsx
  src/components/templates/LoginTemplate/KakaoCallback/CallbackTemplate.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/components/templates/PlanModalTemplate/Register/RegisterModal.tsx
Labels: bug

#12 feat: 도서 검색 후 플랜 등록 구현
  src/api/axios.ts
  src/api/types/book.ts
  src/api/types/planRegister.ts
  src/components/common/Search/SearchList.tsx
  src/components/templates/PlanModalTemplate/Register/RegisterModal.tsx
Labels: enhancement

#13 토큰 오류 수정
  src/api/axios.ts
  src/components/templates/LoginTemplate/KakaoCallback/CallbackTemplate.tsx
Labels: bug

#14 기능수정 및 api 연결
  src/api/axios.ts
  src/api/plan.ts
  src/api/types/planRecord.ts
  src/assets/images/Images.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Calendar/WeekCalendar.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Plan/Dots/Dots.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/mocks/planRecord.ts
  src/store/reducers/userPlan.ts
  src/store/reducers/userSlice.ts
  src/utils/calendar/function.ts
  src/utils/function.ts
Labels: bug, enhancement

#15 feat: 베이직 모달, 덜 읽음 모달, 마이페이지 - 서재, 도감 퍼블리싱
  src/assets/icons/IconArrLeftWhite.tsx
  src/assets/icons/IconArrRightGray.tsx
  src/assets/icons/index.tsx
  src/components/common/Search/SearchList.tsx
  src/components/templates/MyPage/BackTitle.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/EncyclopediaList.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/index.tsx
  src/components/templates/MyPage/MyLibraryTemplate/LibraryList.tsx
  src/components/templates/MyPage/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/MyPage/MyLibraryTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyBanner.tsx
  src/components/templates/MyPageTemplate/MyMenu.tsx
  src/components/templates/MyPageTemplate/MyPageTemplate.tsx
  src/components/templates/MyPageTemplate/MyUser.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/PlanModalTemplate/PlanModal/CharacterModal.tsx
  src/components/templates/PlanModalTemplate/PlanModal/ReadLessModal.tsx
  src/components/templates/PlanModalTemplate/PlanModal/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/PlanModal/SimpleModal.tsx
  src/components/templates/PlanModalTemplate/PlanModal/index.tsx
  src/components/templates/PlanModalTemplate/PlanModalTemplate.tsx
  src/components/templates/PlanModalTemplate/Register/index.tsx
  src/pages/AppMyPage.tsx
  src/pages/MyPage/MyEncyclopedia.tsx
  src/pages/MyPage/MyLibrary.tsx
  src/routers/appRouter.tsx
Labels: enhancement

#16 검색화면 퍼블리싱 및 axios 버그 수정
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/plan.ts
  src/api/types/index.ts
  src/assets/icons/IconReady.tsx
  src/assets/icons/index.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/Book/index.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/components/templates/SearchTemplate/SearchDetail/index.tsx
  src/components/templates/SearchTemplate/SearchInput/SearchInput.tsx
  src/components/templates/SearchTemplate/SearchInput/index.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/SearchMain/index.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchResult/index.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
  src/components/templates/SearchTemplate/Styled.tsx
  src/components/templates/SearchTemplate/index.tsx
  src/hooks/index.ts
  src/hooks/searchOutlet.ts
  src/mocks/books.ts
  src/mocks/index.ts
  src/pages/AppSearch.tsx
  src/pages/AppSearchMain.tsx
  src/pages/AppSearchResult.tsx
  src/routers/appRouter.tsx
  src/store/reducers/bookDetail.ts
  src/store/reducers/bookSearch.ts
  src/store/reducers/index.ts
  src/store/state/store.ts
  src/styles/global-style.ts
  src/utils/Alert/Alert.ts
Labels: bug, enhancement

#17 스타일 오류 수정 외
  src/api/axios.ts
  src/assets/icons/IconReady.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
Labels: bug

#18 Feature/dw
  src/components/common/Form/InputLabel.tsx
  src/components/common/Search/SearchList.tsx
  src/components/templates/MyPage/MyLibraryTemplate/LibraryList.tsx
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreList.tsx
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/MyPage/MyRestoreTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyMenu.tsx
  src/components/templates/PlanModalTemplate/PlanModal/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/PlanModal/SimpleModal.tsx
  src/pages/MyPage/MyRestore.tsx
  src/routers/appRouter.tsx
Labels: enhancement

#20 axios 호출 로직 수정, 버그 수정
  src/App.tsx
  src/api/axios.ts
  src/components/common/ProtectedLogin/ProtectedLogin.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/hooks/axiosInterceptor.ts
  src/mocks/books.ts
  src/pages/AppHome.tsx
  src/store/reducers/userSlice.ts
Labels: bug

#23 기능, 스타일 수정, 추가
  public/blacklogo.svg
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/api/axios.ts
  src/api/plan.ts
  src/assets/images/Images.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
  src/components/templates/SearchTemplate/hooks.ts
  src/hooks/axiosInterceptor.ts
  src/hooks/index.ts
  src/hooks/searchOutlet.ts
  src/mocks/books.ts
  src/store/reducers/bookDetail.ts
  src/store/reducers/bookSearch.ts
  src/store/reducers/userPlan.ts
  src/utils/function.ts
Labels: bug, enhancement

#24 feat: 플랜 수정 기능 데이터 바인딩, 플랜 복구 키값 변경 대기중
  src/api/types/planRecord.ts
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreList.tsx
  src/components/templates/PlanModalTemplate/PlanModal/RegisterModal.tsx
Labels: enhancement

#25 기능수정, 추가
  src/api/plan.ts
  src/api/types/planRegister.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Loading/Dots.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/HomeTemplate/Plan/Dots/Dots.tsx
  src/components/templates/HomeTemplate/Plan/Plan.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/HomeTemplate/Styled.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/MyPage/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/MyPageTemplate/MyPageTemplate.tsx
  src/components/templates/PlanModalTemplate/PlanModalTemplate.tsx
  src/components/templates/PlanModalTemplate/Register/InputLabel.tsx
  src/components/templates/PlanModalTemplate/Register/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/Register/SearchList.tsx
  src/components/templates/PlanModalTemplate/Register/SelectLabel.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
  src/components/templates/SearchTemplate/Styled.tsx
  src/components/templates/SearchTemplate/hooks.ts
  src/store/reducers/userPlan.ts
  src/utils/errors/errors.ts
  src/utils/index.ts
Labels: bug, enhancement

#27 버그 수정 및 기능 추가
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/types/book.ts
  src/api/types/planRegister.ts
  src/assets/images/Images.tsx
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/common/Slider/Slider.tsx
  src/components/common/Slider/index.tsx
  src/components/connections/CheckDay.tsx
  src/components/connections/CheckModal.tsx
  src/components/connections/index.tsx
  src/components/templates/HomeTemplate/Plan/Plan.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/LoginTemplate/KakaoCallback/CallbackTemplate.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/EncyclopediaList.tsx
  src/components/templates/MyPage/MyLibraryTemplate/LibraryList.tsx
  src/components/templates/MyPage/MyMainTemplate/MyBanner.tsx
  src/components/templates/MyPage/MyMainTemplate/MyMenu.tsx
  src/components/templates/PlanModalTemplate/CharacterModal/CharacterModal.tsx
  src/components/templates/PlanModalTemplate/ReadLessModal/CheckBox.tsx
  src/components/templates/PlanModalTemplate/ReadLessModal/ReadLessModal.tsx
  src/components/templates/PlanModalTemplate/ReadLessModal/Styled.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/SearchList/SearchList.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/hooks.ts
  src/declare.d.ts
  src/mocks/books.ts
  src/mocks/index.ts
  src/mocks/planRecord.ts
  src/pages/AppEvent.tsx
  src/pages/AppRoot.tsx
  src/routers/appRouter.tsx
  src/store/reducers/bookDetail.ts
  src/store/reducers/bookSearch.ts
  src/store/reducers/modal.ts
  src/store/reducers/userPlan.ts
  src/styles/global-style.ts
  src/utils/errors/errors.ts
  tsconfig.json
Labels: bug, enhancement

#31 fix. 책 검색 버그 수정
  src/components/templates/SearchTemplate/SearchTemplate.tsx
Labels: bug

#34 버그 수정
  src/assets/images/LoginMainBird.tsx
  src/assets/images/MainLogo.tsx
  src/assets/images/index.tsx
  src/components/common/Modal/Modal.tsx
  src/components/templates/AppTemplate/AppTemplate.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/LoadingTemplate/LoadingTemplate.tsx
  src/components/templates/LoadingTemplate/RouterLoading.tsx
  src/components/templates/LoginTemplate/KakaoCallback/CallbackTemplate.tsx
  src/components/templates/LoginTemplate/LoginTemplate.tsx
  src/components/templates/MyPage/MyLibraryTemplate/LibraryList.tsx
  src/components/templates/MyPage/MyMainTemplate/MyBanner.tsx
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreList.tsx
  src/components/templates/PlanModalTemplate/CharacterModal/CharacterModal.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/styles/global-style.ts
Labels: bug

#35 fix. 플랜달성여부로 달성시 목표치 값 수정 적용
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/store/reducers/userPlan.ts
Labels: bug

#36 fix. 검색 버그 수정
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
Labels: bug

#37 modify. deploy.yml secret env 추가
  .github/workflows/deploy.yml
Labels: bug

#38 버그 수정 및 폴더 리팩토링
  src/components/templates/LoginTemplate/LoginBtn.tsx
  src/components/templates/LoginTemplate/LoginTemplate.tsx
  src/components/templates/MyPage/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/MyPage/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/MyPage/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/MyPageTemplate/BackTitle/BackTitle.tsx
  src/components/templates/MyPageTemplate/BackTitle/index.tsx
  src/components/templates/MyPageTemplate/MyEncyclopediaTemplate/EncyclopediaList.tsx
  src/components/templates/MyPageTemplate/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/MyPageTemplate/MyEncyclopediaTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/Book/Book.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/Book/index.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/LibraryList.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyMainTemplate/MyBanner.tsx
  src/components/templates/MyPageTemplate/MyMainTemplate/MyMainTemplate.tsx
  src/components/templates/MyPageTemplate/MyMainTemplate/MyMenu.tsx
  src/components/templates/MyPageTemplate/MyMainTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyPageTemplate.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/MyRestoreList.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/RestoreBook.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/index.tsx
  src/components/templates/MyPageTemplate/MyUserInfo/MyUser.tsx
  src/components/templates/MyPageTemplate/MyUserInfo/index.tsx
  src/hooks/axiosInterceptor.ts
  src/pages/MyPage/MyEncyclopedia.tsx
  src/pages/MyPage/MyLibrary.tsx
  src/pages/MyPage/MyMain.tsx
  src/pages/MyPage/MyRestore.tsx
Labels: bug

#44 기능 수정, 버그 수정
  src/api/types/planRegister.ts
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/MyPageTemplate/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/PlanModalTemplate/InputLabel/InputLabel.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
Labels: bug

#46 플랜등록시 누락된 속성 추가
  src/api/types/planRegister.ts
  src/components/templates/HomeTemplate/Plan/Plan.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
Labels: bug

#47 버그 수정
  src/store/reducers/userPlan.ts
  src/utils/calendar/function.ts
Labels: bug

#48 fix. 나의서재 다음페이지 무한호출 버그 수정
  src/components/templates/MyPageTemplate/MyLibraryTemplate/MyLibraryTemplate.tsx
Labels: bug

#49 fix. 검색 입력 오류 수정
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/SearchTemplate/hooks.ts
Labels: bug

#50 버그 수정
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
Labels: bug

#51 버그 수정
  src/components/templates/MyPageTemplate/MyRestoreTemplate/RestoreBook.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/SearchList/SearchList.tsx
  src/store/reducers/userPlan.ts
  src/utils/function.ts
Labels: bug

#59 :bug: 등록버튼 표시 조건 오류 수정 외
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/PlanModalTemplate/SearchList/SearchList.tsx
Labels: bug

#60 :bug: 검색 스크롤 초기화, 코드오류 수정
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/LoadingTemplate/LoadingTemplate.tsx
  src/components/templates/LoadingTemplate/RouterLoading.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchMain/SearchMain.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
  src/components/templates/SearchTemplate/hooks.ts
  src/hooks/axiosInterceptor.ts
  src/utils/errors/errors.ts
Labels: bug

#61 :bug: 검색 페이지 호출 오류 수정
  src/components/templates/MyPageTemplate/MyLibraryTemplate/Book.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/PlanModalTemplate/SearchList/SearchList.tsx
  src/components/templates/SearchTemplate/Book/Book.tsx
  src/components/templates/SearchTemplate/SearchResult/SearchResult.tsx
  src/components/templates/SearchTemplate/SearchTemplate.tsx
Labels: bug

#62 :bug: 홈 플랜 두번 호출 오류 수정
  src/components/connections/ProtectedLogin.tsx
  src/components/templates/HomeTemplate/HomeTemplate.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
Labels: bug

#63 :bug: 플랜 count 오류 수정 :memo: index.html 메타태그 추가
  public/index.html
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
Labels: bug

#64 :bug: 버그 수정
  public/blacklogo.png
  public/blacklogo.svg
  public/index.html
  public/manifest.json
  public/purplelogo.png
  public/whitelogo.png
  src/components/connections/ProtectedLogin.tsx
  src/components/templates/AppTemplate/AppTemplate.tsx
  src/components/templates/HomeTemplate/Month/MonthTemplate.tsx
  src/components/templates/HomeTemplate/Month/Styled.tsx
  src/components/templates/HomeTemplate/Plan/Dday/Dday.tsx
  src/components/templates/HomeTemplate/Plan/Dots/Dots.tsx
  src/components/templates/HomeTemplate/Plan/Modal/Modal.tsx
  src/components/templates/HomeTemplate/Plan/Plan.tsx
  src/components/templates/HomeTemplate/Plan/Stamp/Stamp.tsx
  src/components/templates/HomeTemplate/Styled.tsx
  src/components/templates/HomeTemplate/Week/Styled.tsx
  src/components/templates/HomeTemplate/Week/WeekData.tsx
  src/components/templates/HomeTemplate/Week/WeekTemplate.tsx
  src/components/templates/LoginTemplate/LoginTemplate.tsx
  src/components/templates/MyPageTemplate/MyEncyclopediaTemplate/MyEncyclopediaTemplate.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/Book.tsx
  src/components/templates/MyPageTemplate/MyLibraryTemplate/MyLibraryTemplate.tsx
  src/components/templates/MyPageTemplate/MyRestoreTemplate/MyRestoreTemplate.tsx
  src/components/templates/PlanModalTemplate/ReadLessModal/ReadLessModal.tsx
  src/components/templates/PlanModalTemplate/RegisterModal/RegisterModal.tsx
  src/components/templates/SearchTemplate/SearchDetail/SearchDetail.tsx
  src/components/templates/SearchTemplate/SearchDetail/Styled.tsx
  src/components/templates/SearchTemplate/Styled.tsx
  src/styles/global-style.ts
Labels: bug
